import { MappingTableType } from "@moeum/shared/type/component";

export const defaultKeyValues: MappingTableType = [
  { key: "DEFAULT", value: "div" },
  { key: "SLICE", value: "" },
  { key: "FRAME", value: "" },
  { key: "GROUP", value: "" },
  { key: "COMPONENT_SET", value: "" },
  { key: "COMPONENT", value: "" },
  {
    key: "INSTANCE",
    value: {
      popup: "Popup",
      button: "Button",
    },
  },
  { key: "BOOLEAN_OPERATION", value: "" },
  { key: "VECTOR", value: "" },
  { key: "STAR", value: "" },
  { key: "LINE", value: "" },
  { key: "ELLIPSE", value: "" },
  { key: "RECTANGLE", value: "" },
  { key: "TEXT", value: "" },
  { key: "STICKY", value: "" },
  { key: "CONNECTOR", value: "" },
  { key: "SHAPE_WITH_TEXT", value: "" },
  { key: "CODE_BLOCK", value: "" },
  { key: "STAMP", value: "" },
  { key: "WIDGET", value: "" },
  { key: "EMBED", value: "" },
  { key: "LINK_UNFURL", value: "" },
  { key: "MEDIA", value: "" },
  { key: "SECTION", value: "" },
  { key: "HIGHLIGHT", value: "" },
  { key: "WASHI_TAPE", value: "" },
  { key: "TABLE", value: "" },
];
